// Generated by https://quicktype.io

export interface GMPhotos {
    html_attributions: any[];
    result:            Result;
    status:            string;
}

export interface Result {
    photos: Photo[];
}

export interface Photo {
    height:            number;
    html_attributions: string[];
    photo_reference:   string;
    width:             number;
}
